# Enable the feeds that you require by removing the underscore from their names.
# You have to edit the exec line(s) to point to your working directory.
# For Cinematik you have to copy your RSS link to the url field.
# For TorrentLeech you have to copy your RSS link from your edit profile page to the url field.

feeds:
# Cinemageddon
  _cinemageddon:
    rss:
      url: http://cinemageddon.net/rss.xml
      # Force ASCII because the feed is not encoded properly.
      ascii: yes
    regexp:
      from: title
      reject:
        - .+\(XXX\)
        - .+\(OST\)
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the id from the URL.
      - TorrentId:
          from: url
          extract: 'http://cinemageddon\.net/details\.php\?id=(\d+).*'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=cg][id=%(TorrentId)s][title=none]"

# Cinematik
  _cinematik:
    rss:
      url: http://cinematik.net/rss.php?key=AAAAAAAAAAAAAAAA&which=1
      # Force ASCII just to be sure.
      ascii: yes
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the id from the URL.
      - TorrentId:
          from: url
          extract: 'http://cinematik\.net/details\.php\?id=(\d+).*'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=tik][id=%(TorrentId)s][title=none]"

# GFT
  _gft:
    rss:
      # Make sure that at the Generates RSS link page you select Web link as the feed type.
      url: http://www.thegft.org/rss.php?cat=AAAAAAAAAAAAAAAA&passkey=AAAAAAAAAAAAAAAA
      # Force ASCII just to be sure.
      ascii: yes
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the id from the URL.
      - TorrentId:
          from: url
          extract: 'http://www\.thegft\.org/details\.php\?id=(\d+).*'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=gft][id=%(TorrentId)s][title=%(title)s]"

# Karagarga
  _karagarga:
    rss:
      url: https://karagarga.net/rss.php?passkey=AAAAAAAAAAAAAAAA&user=AAAAAAAAAAAAAAAA
      # Force ASCII just to be sure.
      ascii: yes
    regexp:
      from: title
      reject:
        # Ignore literature.
        - .+\[Audiobooks\]$
        - .+\[Books\]$
        - .+\[Comics\]$
        # Ignore music. (Experimental can't be ignored because it is also a movie genre.)
        - .+\[Blues\]$
        - .+\[Classical\]$
        - .+\[Country\]$
        - .+\[Electronica\]$
        - .+\[Exotica\]$
        - .+\[Folk\]$
        - .+\[Funk\]$
        - .+\[Indie\]$
        - .+\[Jazz\]$
        - .+\[Latin\]$
        - .+\[Live\]$
        - .+\[Metal\]$
        - .+\[Punk & Hardcore\]$
        - .+\[Rap & Hiphop\]$
        - .+\[Reggae\]$
        - .+\[Rock\]$
        - .+\[Soul\]$
        - .+\[Soundtrack\]$
        - .+\[World\]$
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the ID from the URL.
      - TorrentId:
          from: url
          extract: 'http://karagarga.net/details.php\?id=(\d+)'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=kg][id=%(TorrentId)s][title=none]"

# SceneAccess
  _sceneaccess:
    rss:
      # Make sure that at the RSS Link Generator you select Web link as the feed type.
      url: http://www.sceneaccess.org/rss.php?cat=AAAAAAAAAAAAAAAA&passkey=AAAAAAAAAAAAAAAA
      # Force ASCII just to be sure.
      ascii: yes
    accept_all: yes
    manipulate:
      # Create TorrentId field by extracting the id from the URL.
      - TorrentId:
          from: url
          extract: 'http://www\.sceneaccess\.org/details\.php\?id=(\d+).*'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=scc][id=%(TorrentId)s][title=%(title)s]"

# TorrentLeech
  _torrentleech:
    rss:
      url: http://rss.torrentleech.org/AAAAAAAAAAAAAAAA
      # Get the category field from the RSS.
      other_fields: [category]
    regexp:
      from: category
      accept:
        - BDRip
        - DVDRip/DVDScreener
        - HD
      # HD matches Epised HD too so Episoded HD is needed in the reject list. Other categories will remain undecided and won't be accepted, there is no need for adding them here.
      reject:
        - Episodes HD
    manipulate:
      # Create TorrentId field by extracting the ID from the URL.
      - TorrentId:
          from: url
          extract: 'http://www\.torrentleech\.org/rss/download/(\d+)/.*'
    exec: echo >> "/path to WorkingDirectory/announcement/[source=tl][id=%(TorrentId)s][title=%(title)s]"